### ISSUE TITLE
TYPO3_MODE is deprecated

### ISSUE THREAD

**Issue by gilbertsoft** [thomasrawiel/whatchado#1]
Just saw a little issue with your [security gate in ext_localconf.php](https://github.com/thomasrawiel/whatchado/blob/8fc68faafbd0d3adc61afb8f54f88bfe1a40ddb4/ext_localconf.php#L2). `TYPO3_MODE` is deprecated and you should use `TYPO3` instead see [change log](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html#typo3-mode-usage-as-global-script-file-security-gate). The new constant is available since 10.4.11 see https://github.com/TYPO3/typo3/commit/1462f2a6cd501ae89166a55e97a7733d7f5a5ca4.

**Comment by thomasrawiel** [comment]
Thanks for the hint. 

Fixed in [1.1.1](https://github.com/thomasrawiel/whatchado/commit/d2e8fdba022b4cc6e398ca332b73e99aa8316058)
